'use client';

import React, { createContext, useCallback, useContext, useEffect, useState } from 'react';
import type { Language } from '@/lib/types';

const STORAGE_KEY = '@walu_language';

const translations = {
  en: {
    // Nav
    nav: {
      home: 'Home',
      transactions: 'Transactions',
      reports: 'Reports',
      budgets: 'Budgets',
      settings: 'Settings',
    },
    // Auth
    auth: {
      signIn: 'Sign In',
      signUp: 'Sign Up',
      signOut: 'Sign Out',
      email: 'Email',
      password: 'Password',
      firstName: 'First Name',
      lastName: 'Last Name',
      forgotPassword: 'Forgot password?',
      sendReset: 'Send reset email',
      noAccount: "Don't have an account? Sign Up",
      hasAccount: 'Already have an account? Sign In',
      selectAvatar: 'Select an avatar',
      welcomeBack: 'Welcome back',
      createAccount: 'Create Account',
      continueAsGuest: 'Continue as guest',
      resetPassword: 'Reset Password',
      newPassword: 'New Password',
      confirmPassword: 'Confirm Password',
      updatePassword: 'Update Password',
      passwordMismatch: 'Passwords do not match.',
      passwordShort: 'Password must be at least 6 characters.',
      checkEmail: 'Check your email',
      resetSent: 'If an account exists for that email, we sent password reset instructions.',
      accountCreated: 'Account created! Check your inbox to confirm your email.',
      required: 'Required',
      sendingEmail: 'Sending email...',
      avatarRequired: 'Please select an avatar.',
      fillAllFields: 'Please fill in all fields.',
      nameRequired: 'Please enter your first and last name.',
    },
    // Common
    common: {
      loading: 'Loading...',
      save: 'Save',
      cancel: 'Cancel',
      delete: 'Delete',
      edit: 'Edit',
      create: 'Create',
      confirm: 'Confirm',
      close: 'Close',
      back: 'Back',
      search: 'Search',
      filter: 'Filter',
      all: 'All',
      yes: 'Yes',
      no: 'No',
      error: 'Error',
      success: 'Success',
    },
    // Reports
    reports: {
      title: 'Reports',
      overview: 'Overview',
      categories: 'Categories',
      trend: 'Trend',
      tools: 'Accounts',
      expense: 'Expenses',
      income: 'Income',
      net: 'Net',
      noData: 'No data for this period',
      vsLastMonth: 'vs last month',
      monthly: 'Monthly',
      yearly: 'Yearly',
      allAccounts: 'All accounts',
      last6Months: 'Last 6 months',
    },
    // Budgets
    budgets: {
      title: 'Budgets',
      addBudget: 'Add budget',
      editBudget: 'Edit budget',
      deleteBudget: 'Delete budget',
      confirmDelete: 'Delete this budget?',
      noBudgets: 'No budgets yet. Add one!',
      name: 'Budget name',
      namePlaceholder: 'e.g. Food, Entertainment...',
      amount: 'Amount',
      category: 'Category',
      total: 'Total spending',
      budgeted: 'Budgeted',
      spent: 'Spent',
      remaining: 'Remaining',
      over: 'Over budget',
      period: 'Period',
      monthly: 'Monthly',
      type: 'Type',
      categoryBudget: 'By category',
      totalBudget: 'Total',
      alertThreshold: 'Alert at (%)',
      of: 'of',
      history: 'History',
      overview: 'Overview',
      totalBudgeted: 'Total budgeted',
      totalSpent: 'Total spent',
    },
    // Transactions
    transactions: {
      title: 'Transactions',
      expense: 'Expense',
      income: 'Income',
      transfer: 'Transfer',
      all: 'All',
      addTransaction: 'Add transaction',
      editTransaction: 'Edit transaction',
      confirmDelete: 'Delete this transaction?',
      noTransactions: 'No transactions this month',
      account: 'Account',
      fromAccount: 'From account',
      toAccount: 'To account',
      category: 'Category',
      subcategory: 'Subcategory',
      label: 'Label',
      note: 'Note',
      date: 'Date',
      amount: 'Amount',
      destinationAmount: 'Destination amount',
      totalIncome: 'Income',
      totalExpense: 'Expenses',
      balance: 'Balance',
      today: 'Today',
      yesterday: 'Yesterday',
      noLabel: 'No label',
      optional: 'Optional',
      noCategory: 'No category',
      sameAsSent: 'Same as sent',
    },
    // Settings
    settings: {
      title: 'Settings',
      categories: 'Categories',
      categoriesDesc: 'Manage expense and income categories',
      labels: 'Labels',
      labelsDesc: 'Manage tags for your transactions',
      profile: 'Profile',
      profileDesc: 'Edit your personal information',
      security: 'Security',
      securityDesc: 'Change password and security options',
      appearance: 'Appearance',
      appearanceDesc: 'Theme, language and display preferences',
      comingSoon: 'Coming soon',
      // Profile
      firstName: 'First name',
      lastName: 'Last name',
      avatar: 'Avatar',
      saveChanges: 'Save changes',
      saved: 'Changes saved',
      // Security
      currentPassword: 'Current password',
      newPassword: 'New password',
      confirmPassword: 'Confirm new password',
      updatePassword: 'Update password',
      passwordUpdated: 'Password updated successfully',
      passwordMismatch: 'Passwords do not match.',
      passwordShort: 'Password must be at least 6 characters.',
      currentPasswordIncorrect: 'Current password is incorrect.',
      dangerZone: 'Danger zone',
      deleteAccount: 'Delete account',
      deleteAccountDesc: 'Permanently delete your account and all data.',
      confirmDeleteAccount: 'Type DELETE to confirm',
      // Appearance
      theme: 'Theme',
      themeLight: 'Light',
      themeDark: 'Dark',
      themeSystem: 'System',
      language: 'Language',
    },
    // Categories
    categories: {
      title: 'Categories',
      expense: 'Expense',
      income: 'Income',
      addCategory: 'Add category',
      editCategory: 'Edit category',
      deleteCategory: 'Delete category',
      confirmDelete: 'Delete this category?',
      name: 'Category name',
      namePlaceholder: 'e.g. Food, Transport...',
      color: 'Color',
      icon: 'Icon',
      subcategories: 'Subcategories',
      addSubcategory: 'Add subcategory',
      subcategoryPlaceholder: 'e.g. Restaurants, Uber...',
      noCategories: 'No categories yet. Add one!',
      subcategory: 'subcategory',
      subcategories_plural: 'subcategories',
    },
    // Labels
    labels: {
      title: 'Labels',
      addLabel: 'Add label',
      placeholder: 'New label...',
      noLabels: 'No labels yet. Add one!',
      editLabel: 'Edit label',
    },
  },
  es: {
    nav: {
      home: 'Inicio',
      transactions: 'Transacciones',
      reports: 'Reportes',
      budgets: 'Presupuestos',
      settings: 'Ajustes',
    },
    auth: {
      signIn: 'Iniciar sesión',
      signUp: 'Registrarme',
      signOut: 'Cerrar sesión',
      email: 'Correo electrónico',
      password: 'Contraseña',
      firstName: 'Nombre',
      lastName: 'Apellido',
      forgotPassword: 'Olvidé mi contraseña',
      sendReset: 'Enviar correo de recuperación',
      noAccount: '¿No tienes cuenta? Regístrate',
      hasAccount: '¿Ya tienes cuenta? Inicia sesión',
      selectAvatar: 'Selecciona un avatar',
      welcomeBack: 'Bienvenido de nuevo',
      createAccount: 'Crear cuenta',
      continueAsGuest: 'Continuar como invitado',
      resetPassword: 'Restablecer contraseña',
      newPassword: 'Nueva contraseña',
      confirmPassword: 'Confirmar contraseña',
      updatePassword: 'Actualizar contraseña',
      passwordMismatch: 'Las contraseñas no coinciden.',
      passwordShort: 'La contraseña debe tener al menos 6 caracteres.',
      checkEmail: 'Revisa tu correo',
      resetSent: 'Si existe una cuenta con ese correo, te enviamos instrucciones para restablecer tu contraseña.',
      accountCreated: '¡Cuenta creada! Revisa tu correo para confirmar tu cuenta.',
      required: 'Obligatorio',
      sendingEmail: 'Enviando correo...',
      avatarRequired: 'Por favor selecciona un avatar.',
      fillAllFields: 'Por favor completa todos los campos.',
      nameRequired: 'Por favor ingresa tu nombre y apellido.',
    },
    common: {
      loading: 'Cargando...',
      save: 'Guardar',
      cancel: 'Cancelar',
      delete: 'Eliminar',
      edit: 'Editar',
      create: 'Crear',
      confirm: 'Confirmar',
      close: 'Cerrar',
      back: 'Atrás',
      search: 'Buscar',
      filter: 'Filtrar',
      all: 'Todos',
      yes: 'Sí',
      no: 'No',
      error: 'Error',
      success: 'Éxito',
    },
    reports: {
      title: 'Reportes',
      overview: 'Resumen',
      categories: 'Categorías',
      trend: 'Tendencia',
      tools: 'Cuentas',
      expense: 'Gastos',
      income: 'Ingresos',
      net: 'Neto',
      noData: 'Sin datos para este período',
      vsLastMonth: 'vs mes anterior',
      monthly: 'Mensual',
      yearly: 'Anual',
      allAccounts: 'Todas las cuentas',
      last6Months: 'Últimos 6 meses',
    },
    budgets: {
      title: 'Presupuestos',
      addBudget: 'Agregar presupuesto',
      editBudget: 'Editar presupuesto',
      deleteBudget: 'Eliminar presupuesto',
      confirmDelete: '¿Eliminar este presupuesto?',
      noBudgets: 'Sin presupuestos. ¡Agrega uno!',
      name: 'Nombre',
      namePlaceholder: 'Ej: Comida, Entretenimiento...',
      amount: 'Monto',
      category: 'Categoría',
      total: 'Gasto total',
      budgeted: 'Presupuestado',
      spent: 'Gastado',
      remaining: 'Restante',
      over: 'Excedido',
      period: 'Período',
      monthly: 'Mensual',
      type: 'Tipo',
      categoryBudget: 'Por categoría',
      totalBudget: 'Total',
      alertThreshold: 'Alerta en (%)',
      of: 'de',
      history: 'Historial',
      overview: 'Resumen',
      totalBudgeted: 'Total presupuestado',
      totalSpent: 'Total gastado',
    },
    transactions: {
      title: 'Transacciones',
      expense: 'Gasto',
      income: 'Ingreso',
      transfer: 'Transferencia',
      all: 'Todos',
      addTransaction: 'Agregar transacción',
      editTransaction: 'Editar transacción',
      confirmDelete: '¿Eliminar esta transacción?',
      noTransactions: 'Sin transacciones este mes',
      account: 'Cuenta',
      fromAccount: 'Cuenta origen',
      toAccount: 'Cuenta destino',
      category: 'Categoría',
      subcategory: 'Subcategoría',
      label: 'Etiqueta',
      note: 'Nota',
      date: 'Fecha',
      amount: 'Monto',
      destinationAmount: 'Monto destino',
      totalIncome: 'Ingresos',
      totalExpense: 'Gastos',
      balance: 'Balance',
      today: 'Hoy',
      yesterday: 'Ayer',
      noLabel: 'Sin etiqueta',
      optional: 'Opcional',
      noCategory: 'Sin categoría',
      sameAsSent: 'Igual al enviado',
    },
    settings: {
      title: 'Ajustes',
      categories: 'Categorías',
      categoriesDesc: 'Gestiona categorías de gastos e ingresos',
      labels: 'Etiquetas',
      labelsDesc: 'Gestiona etiquetas para tus transacciones',
      profile: 'Perfil',
      profileDesc: 'Edita tu información personal',
      security: 'Seguridad',
      securityDesc: 'Cambia tu contraseña y opciones de seguridad',
      appearance: 'Apariencia',
      appearanceDesc: 'Tema, idioma y preferencias de visualización',
      comingSoon: 'Próximamente',
      // Perfil
      firstName: 'Nombre',
      lastName: 'Apellido',
      avatar: 'Avatar',
      saveChanges: 'Guardar cambios',
      saved: 'Cambios guardados',
      // Seguridad
      currentPassword: 'Contraseña actual',
      newPassword: 'Nueva contraseña',
      confirmPassword: 'Confirmar nueva contraseña',
      updatePassword: 'Actualizar contraseña',
      passwordUpdated: 'Contraseña actualizada correctamente',
      passwordMismatch: 'Las contraseñas no coinciden.',
      passwordShort: 'La contraseña debe tener al menos 6 caracteres.',
      currentPasswordIncorrect: 'La contraseña actual es incorrecta.',
      dangerZone: 'Zona de peligro',
      deleteAccount: 'Eliminar cuenta',
      deleteAccountDesc: 'Elimina permanentemente tu cuenta y todos tus datos.',
      confirmDeleteAccount: 'Escribe ELIMINAR para confirmar',
      // Apariencia
      theme: 'Tema',
      themeLight: 'Claro',
      themeDark: 'Oscuro',
      themeSystem: 'Sistema',
      language: 'Idioma',
    },
    categories: {
      title: 'Categorías',
      expense: 'Gasto',
      income: 'Ingreso',
      addCategory: 'Agregar categoría',
      editCategory: 'Editar categoría',
      deleteCategory: 'Eliminar categoría',
      confirmDelete: '¿Eliminar esta categoría?',
      name: 'Nombre de categoría',
      namePlaceholder: 'Ej: Comida, Transporte...',
      color: 'Color',
      icon: 'Icono',
      subcategories: 'Subcategorías',
      addSubcategory: 'Agregar subcategoría',
      subcategoryPlaceholder: 'Ej: Restaurantes, Uber...',
      noCategories: 'Sin categorías. ¡Agrega una!',
      subcategory: 'subcategoría',
      subcategories_plural: 'subcategorías',
    },
    labels: {
      title: 'Etiquetas',
      addLabel: 'Agregar etiqueta',
      placeholder: 'Nueva etiqueta...',
      noLabels: 'Sin etiquetas. ¡Agrega una!',
      editLabel: 'Editar etiqueta',
    },
  },
} as const;

type TranslationKey = typeof translations['en'];

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: TranslationKey;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('es');

  useEffect(() => {
    const stored = localStorage.getItem(STORAGE_KEY) as Language | null;
    if (stored === 'en' || stored === 'es') {
      setLanguageState(stored);
    }
  }, []);

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem(STORAGE_KEY, lang);
  }, []);

  const t = translations[language] as TranslationKey;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
